infiniCite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paper.urls')),
    path('user/', include('user.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paper/urls.py
# BEGIN: 5d8f9a2b8d7c
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import LibraryViewSet, LibraryPaperViewSet, PaperView, LibraryView
from . import views

app_name = "paper"
router = DefaultRouter()
router.register(r"libraries", LibraryViewSet)
# TODO: add unshare endpoint
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("graph/", views.graph, name="graph"),
    path("libraries/papers", PaperView.as_view(), name="library-all-papers"),
    path(
        "libraries/<int:library_pk>/papers/",
        LibraryView.as_view(),
        name="library-paper-list",
    ),
    path("api/", include(router.urls)),
    path("api/autocomplete/", views.autocomplete, name="autocomplete"),
    path(
        "api/libraries/<int:library_pk>/share/",
        LibraryViewSet.as_view({"post": "share", "delete": "share"}),
        name="library-share",
    ),
    path(
        "api/libraries/<int:library_pk>/papers/",
        LibraryPaperViewSet.as_view({"post": "create"}),
        name="library-paper-add",
    ),
    path(
        "api/libraries/<int:library_pk>/papers/<str:pk>/",
        LibraryPaperViewSet.as_view({"delete": "destroy"}),
        name="library-paper-remove",
    ),
    path(
        "api/libraries/<int:library_pk>/papers/<str:pk>/move/",
        LibraryPaperViewSet.as_view({"post": "move"}),
        name="library-paper-move",
    ),
    path(
        "api/paper/<str:paper_pk>/libraries/",
        LibraryPaperViewSet.as_view(
            {"post": "add_to_libraries", "delete": "remove_from_libraries"}
        ),
        name="paper-batch-operations",
    ),
    path(
        "api/paper/search/",
        LibraryPaperViewSet.as_view({"post": "search"}),  # later change to post
        name="paper-search",
    ),
    path(
        "api/paper/semantic-search/",
        LibraryPaperViewSet.as_view({"post": "semantic_search"}),
        name="paper-semantic-search",
    ),
    path(
        "api/paper/natural-language-search/",
        LibraryPaperViewSet.as_view({"post": "natural_language_search"}),
        name="paper-natural-language-search",
    ),
    path("paper/home_page.html", views.home_page, name="home_page"),
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # create customized logout view
    path('reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset'),
    path('reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # TODO: change url path to `api/user/search`
    path('api/search/', views.AccountViewSet.as_view({'post': 'search'}), name='search'),
    path('edit/', views.edit, name='edit'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paper/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from author.models import Author, PublicationVenue
from user.models import Account


class Paper(models.Model):
    paperId= models.CharField(max_length=255, primary_key=True)
    url = models.URLField(blank=True, null=True)
    title = models.CharField(max_length=511)
    abstract = models.TextField(blank=True, null=True)
    fieldsOfStudy = ArrayField(models.CharField(max_length=255), blank=True, default=list)
    referenceCount = models.IntegerField(null=True)
    citationCount = models.IntegerField(null=True)
    openAccessPdf = models.URLField(blank=True, null=True)
    embedding = ArrayField(models.FloatField(), blank=True, null=True)
    tldr = models.TextField(blank=True, null=True)
    publicationDate = models.DateField(blank=True, null=True)
    authors = models.ManyToManyField(Author, related_name='papers', blank=True, default=list)
    publicationVenue = models.ForeignKey(PublicationVenue, related_name='papers', blank=True, on_delete=models.CASCADE, null=True)
    publicationTypes = ArrayField(models.CharField(max_length=255), blank=True, default=list)
    references = models.ManyToManyField('self', related_name='citations', symmetrical=False, blank=True, default=list)

# TODO: add date created field
# TODO: add user permissions field: view, edit, full control
class Library(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='libraries')
    papers = models.ManyToManyField(Paper, related_name='libraries', blank=True, default=list)
    sharedWith = models.ManyToManyField(Account, related_name='sharedLibraries', blank=True, default=list)

paper/forms.py
from typing import Any, Mapping, Optional, Type, Union
from django import forms
from django.forms.utils import ErrorList

class SearchForm(forms.Form):
    query = forms.CharField(max_length=200)
    page = forms.IntegerField(min_value=1, initial=1, required=False)
    searchPaper = forms.BooleanField(required=False, initial=True)

paper/views.py
from django.http import HttpResponseForbidden, JsonResponse
from elasticsearch_dsl import tokenizer
import requests
import json
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from rest_framework import status, viewsets
from rest_framework.response import Response
from author.services import AuthorService
from paper.serializers import LibrarySerializer
from paper.services import PaperService
from user.models import Account

from .exceptions import *

# Create your views here.
from .forms import SearchForm
from .models import Library, Paper
from .serializers import LibrarySerializer, PaperSerializer
from infiniCite.settings import ELASTICSEARCH_CLIENT as es
from infiniCite.settings import OPENAI_CLIENT as oa
from infiniCite.specter import tokenizer, model


from functools import wraps
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from .models import Library

VALID_SORT_BYS = ["title", "publicationDate", "citationCount", "referenceCount"]
paper_service = PaperService()
author_service = AuthorService()


def index(request):
    form = SearchForm()
    return render(request, "paper/index.html", {"form": form})


def search(request):
    if request.method == "GET":
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            page = form.cleaned_data["page"] or 1
            searchPaper = form.cleaned_data["searchPaper"]
            return handle_search(request, query, page, searchPaper)
        else:
            return render(request, "paper/index.html", {"form": form})
    else:
        return redirect("paper:index")


def handle_search(request, query, page, searchPaper):
    if query:
        if searchPaper:
            context = search_papers(query, page)
            return render(request, "paper/paper-results.html", context)
        else:
            context = search_authors(query, page)
            return render(request, "paper/author-results.html", context)
    else:
        return redirect("paper:index")


def search_papers(query, page=1):
    data = paper_service.search_external_papers(query, page)
    total = data.get("total", 0)
    total_pages = total // paper_service.RECORDS_PER_PAGE + 1

    # Calculate the range of pages to show
    start = max(1, page - 3)
    end = min(total_pages, page + 3) + 1
    pages_to_show = range(start, end)

    return {
        "papers": data,
        "page": page,
        "query": query,
        "total_pages": total_pages,
        "pages_to_show": pages_to_show,
        "searchPaper": True,
    }


def search_authors(query, page=1):
    data = author_service.search_external_authors(query, page)
    total = data.get("total", 0)
    total_pages = total // author_service.RECORDS_PER_PAGE + 1

    # Calculate the range of pages to show
    start = max(1, page - 3)
    end = min(total_pages, page + 3) + 1
    pages_to_show = range(start, end)

    return {
        "authors": data,
        "page": page,
        "query": query,
        "total_pages": total_pages,
        "pages_to_show": pages_to_show,
        "searchPaper": False,
    }


def autocomplete(request):
    query = request.GET.get("query")
    if query:
        # Call the API with the search input
        return JsonResponse(paper_service.autocomplete(query), safe=False)
    else:
        return redirect("index")  # redirect to index view


def home_page(request):
    account = request.user.account
    libraries = Library.objects.filter(owner=account)
    list_libraryPaperRec = []
    for library in libraries:
        libraryName = library.name
        libraryPapers = library.papers.all().values()
        libraryPapersIds = []
        for paper in libraryPapers:
            libraryPapersIds.append(paper["paperId"])
        if len(libraryPapersIds) > 0:
            recommendation = getRecommendation(libraryPapersIds)
            list_libraryPaperRec.append((libraryName, recommendation))
    print(list_libraryPaperRec)
    return render(
        request, "paper/home_page.html", {"library_paper_recommendations": list_libraryPaperRec}
    )


def getRecommendation(Ids):
    RECOMMENDATION = "http://api.semanticscholar.org/recommendations/v1/papers/?limit=1&fields=authors,title,abstract,publicationTypes,url,publicationVenue"
    body = {
        "positivePaperIds": Ids,
    }
    response = requests.request("POST", RECOMMENDATION, data=json.dumps(body))
    return response.json()


def check_library_access(permission_required):
    """
    A decorator function that checks if the user has access to a library.

    Args:
        permission_required (str): The permission required to access the library. Can be "read" or "edit".

    Returns:
        function: The decorated view function.
    """

    def decorator(view_func):
        @wraps(view_func)
        def _wrapped_view(self, request, *args, **kwargs):
            library_pk = kwargs.get("library_pk")

            if library_pk:
                library = Library.objects.get(pk=library_pk)
                if permission_required == "read":
                    if (
                        library.owner != request.user.account
                        and request.user.account not in library.sharedWith.all()
                    ):
                        return HttpResponseForbidden(
                            "You do not have read access to this library."
                        )
                elif permission_required == "edit":
                    if library.owner != request.user.account:
                        return HttpResponseForbidden(
                            "You do not have edit access to this library."
                        )
                else:
                    return HttpResponseForbidden("Invalid permission.")

            return view_func(self, request, *args, **kwargs)

        return _wrapped_view

    return decorator


# TODO: test order by
class LibraryView(View):
    @check_library_access("read")
    def get(self, request, *args, **kwargs):
        library = get_object_or_404(Library, pk=kwargs["library_pk"])

        sort_by = request.GET.get("sort_by", "title")  # default to ordering by title
        if sort_by not in VALID_SORT_BYS:
            sort_by = "title"

        papers = library.papers.order_by(sort_by)
        serializer = PaperSerializer(papers, many=True, context={"request": request})
        return render(
            request,
            "paper/library-papers.html",
            {"data": {"name": library.name, "papers": serializer.data}},
        )


class PaperView(View):
    def get(self, request, *args, **kwargs):
        account = request.user.account
        order_by = request.GET.get("order_by", "title")  # default to ordering by title
        if order_by not in VALID_SORT_BYS:
            order_by = "title"

        papers = (
            paper_service.queryset.filter(libraries__owner=account).distinct().order_by(order_by)
        )
        serializer = PaperSerializer(papers, many=True, context={"request": request})
        return render(
            request,
            "paper/library-papers.html",
            {"data": {"name": "All papers", "papers": serializer.data}},
        )


# TODO: add login required
# TODO: refactor it into three viewsets
# TODO: show saved libraries in search results?
class LibraryViewSet(viewsets.ModelViewSet):
    queryset = Library.objects.all()
    serializer_class = LibrarySerializer
    account_queryset = Account.objects.all()

    def create(self, request, *args, **kwargs):
        userId = request.user.id
        owner = self.account_queryset.get(user_id=userId)

        # create a library
        library = self.queryset.create(owner=owner, name=request.data["name"])
        paper_ids = list(map(lambda paper: paper["paperId"], request.data.get("papers", [])))
        library.papers.set(paper_ids)

        serializer = self.serializer_class(library, context={"request": request})
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    @check_library_access("edit")
    def share(self, request, *args, **kwargs):
        """
        Shares or unshares a library with an account.

        Args:
            request: The HTTP request object.
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.

        Returns:
            A Response object with a status code of 200 if the library was successfully shared or unshared, or a status code of 404 if either the library or account was not found.
        """
        library_pk = kwargs["library_pk"]
        account_id = request.data["account_id"]
        if not (library_pk and account_id):
            return Response(status=status.HTTP_400_BAD_REQUEST)

        lib = self.queryset.get(pk=library_pk)
        acc = self.account_queryset.get(pk=account_id)
        if lib and acc:
            if request.method == "POST":
                lib.sharedWith.add(acc)
            elif request.method == "DELETE":
                lib.sharedWith.remove(acc)
            return Response(status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_404_NOT_FOUND)


class LibraryPaperViewSet(viewsets.ViewSet):
    queryset = Paper.objects.all()
    library_queryset = Library.objects.all()
    serializer_class = LibrarySerializer
    paper_service = PaperService()

    @check_library_access("edit")
    def create(self, request, *args, **kwargs):
        """
        Adds multiple papers to a library.

        Args:
            request: The HTTP request object.
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.

        Returns:
            A Response object with a status code of 201 if the papers were successfully added to the library, or a status code of 400 if any of the papers were not found.
        """

paper/templates/paper/author-results.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'paper/css/result-page.css'%}">
{% endblock %}

{% block content %}
<h1>Authors</h1>
<table>
  <tr>
    <th>Author ID</th>
    <th>Name</th>
    <th>External IDs</th>
    <th>Affiliations</th>
    <th>Paper Count</th>
    <th>Citation Count</th>
    <th>H-Index</th>
  </tr>
  {% for author in authors.data %}
  <tr>
    <td>{{ author.authorId }}</td>
    <td>{{ author.name }}</td>
    <td>{{ author.externalIds|join:", " }}</td>
    <td>{{ author.affiliations|join:", " }}</td>
    <td>{{ author.paperCount }}</td>
    <td>{{ author.citationCount }}</td>
    <td>{{ author.hIndex }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}
{% include 'pagination.html' with page=page query=query total_page=total_page searchPaper=searchPaper%}

paper/templates/paper/graph.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Citation Graph</title>
  <link rel="stylesheet" type="text/css" href="{% static 'paper/graph.css' %}">
  <script src="https://d3js.org/d3.v5.min.js"></script>
</head>

<body>
  {{ nodes|json_script:"nodes" }}
  {{ edges|json_script:"edges" }}
  <svg id="graph" width="1440" height="960"></svg>
  <script type=text/javascript src="{% static 'paper/js/graph.js' %}"></script>
</body>

</html>

paper/templates/paper/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'paper/css/index.css'%}">
{% endblock %}

{% block content %}
<div class="my-container">
  <div class="switch-button">
    <input class="switch-button-checkbox" type="checkbox" id="toggle-author-search" onchange="toggleSearchType(this)">
    <label class="switch-button-label" for="toggle-author-search">
      <div class="switch-button-slider"></div>
      <span class="switch-button-label-span">Paper</span>
    </label>
  </div>

  <div class="form-container">
    <form action="{% url 'paper:search' %}" method="get" class="search-bar">
      <input type="text" name="query" id="query-field" placeholder="Search..."
        value="{{ form.query.value|default_if_none:'' }}" autocomplete="on">
      <input type="hidden" name="page" value="{{ form.page.value|default:1 }}">
      <input type="hidden" name="searchPaper" value="true" id="paper-search">
      <ul id="autocomplete-results" class="autocomplete-active"></ul>
      <button class="search-button" type="submit">
        <img src="{% static 'paper/images/search.png' %}" alt="search-icon">
      </button>
    </form>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  function toggleSearchType(checkbox) {
    var searchPaper = document.getElementById("paper-search");
    if (checkbox.checked) {
      searchPaper.value = "false";
    } else {
      searchPaper.value = "true";
    }
  }
</script>
{% endblock %}

paper/templates/paper/library-papers.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'paper/css/result-page.css'%}">
<link rel="stylesheet" href="{%static 'paper/css/library-papers.css'%}">
{% endblock %}

{% block content %}

<h1> <i class="bi bi-folder-fill icon large"></i> {{data.name}}</h1>
<div class="results">
  {% for paper in data.papers %}
  <div class="paper" style="display: flex; justify-content: space-between;" paper-id="{{ paper.paperId }}">
    <div class="paper-left">
      <h2>
        <a href="{{ paper.url }}">
          {{ paper.title }}
        </a>
      </h2>
      <div class="authors">
        {% for author in paper.authors %}
        {{ author.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </div>
      <div class="publication-venue">
        <a href="{{paper.publicationVenue.url}}">
          {{ paper.publicationVenue.name }}
        </a>
      </div>
      <!-- TODO: display filled bookmark if the paper is in library, optimize the backend so don't have to save the same
      paper twice -->
      <div class="paper-options-container">
        <div class="types">
          {% for type in paper.publicationTypes %}
          <span class="type-tag">
            {% if type == 'JournalArticle' %}
            Journal
            {% else %}
            {{ type }}
            {% endif %}
          </span>
          {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <div class="paper-options-container-2">
          <div class="paper-option-container-3">
            <div class="function-icon-container" title="Manage Paper">
              <input type="hidden" value="{{paper.paperId}}" id="manage-paper-{{paper.paperId}}">
              {{ paper.libraries | json_script:"librariesData" }}
              <i class="bi bi-folder-symlink-fill icon" onclick="managePaperOnClick(`{{paper.paperId}}`)"></i>
            </div>
            {% with num_libraries=paper.libraries|length %}
            {% if num_libraries > 3 %}
            {% for library in paper.libraries|slice:":3" %}
            <span class="library-option-text">
              <a href="{% url 'paper:library-paper-list' library_pk=library.id %}">
                {{ library.name }}
              </a>
              {% if not forloop.last %} &#x2022 {% endif %}
            </span>
            {% endfor %}
            <span class="library-option-text"> +{{ num_libraries|add:"-3" }}</span>
            {% else %}
            {% for library in paper.libraries %}
            <span class="library-option-text">
              <a href="{% url 'paper:library-paper-list' library_pk=library.id %}">
                {{library.name }}
              </a>
              {% if not forloop.last %} &#x2022 {% endif %}
            </span>
            {% endfor %}
            {% endif %}
            {% endwith %}
          </div>
          <div class="paper-option-container-3">
            <div class="function-icon-container" title="Remove from library">
              <i class="bi bi-bookmark-dash-fill icon"
                onclick="removePaperOnClick('{{ paper.paperId }}', `{{ data.id }}`)"></i>
            </div>
            <span class="library-option-text">Remove</span>
          </div>
        </div>
        {% endif %}

        {% if data.abc %}
        {% endif %}
      </div>

      <p class="abstract">
        {{ paper.abstract }}
      </p>
    </div>
    <div style="clear: both;"></div>

    <div class="paper-right">
      <div>
        <div class="local-network">Paper Specifics</div>
        <p>
          <i class="bi bi-calendar icon small"></i>
          Year: {{ paper.publicationDate }}
        </p>
        <p>
          <i class="bi bi-blockquote-left icon large"></i>
          References: {{ paper.referenceCount }}
        </p>
        <p>
          <i class="bi bi-quote icon"></i>
          Citations: {{ paper.citationCount }}
        </p>
        <p>
          <i class="bi bi-tags icon"></i>
          Fields of Study:
          {% for field in paper.fieldsOfStudy %}
          <span class="field-of-study">{{ field }} </span>
          {% endfor %}
        </p>
      </div>
      <div>
        <div class="divider"></div>
        <div class="local-network">Local Network Visualization</div>
        <form action="{% url 'paper:graph' %}">
          <input type="hidden" name="paperId" value="{{ paper.paperId }}">
          <div>
            <input type="radio" id="citation-graph" name="graphType" value="citations" checked>
            <label for="citation-graph" style="font-size: smaller;">Citation Graph</label>
          </div>
          <div>
            <input type="radio" id="reference-graph" name="graphType" value="references">
            <label for="reference-graph" style="font-size: smaller;">Reference Graph</label>
          </div>
          <div class="view-button-container">
            <button class="btn btn-primary view-button" type="submit">View</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% empty %}
  <h2 class="empty-result">Your library {{data.name}} is empty!</h2>
  <!-- svg for 404 page on dribble -->
  <!-- Recommended paper based on collection name -->
  {% endfor %}
  {% include 'pagination.html' with page=page query=query total_pages=total_pages searchPaper=searchPaper%}
</div>
{% endblock %}

{% block js %}
<script src="{% static 'paper/js/fields-of-study.js' %}"></script>
<script src="{% static 'paper/js/paper-results.js' %}"></script>
{% endblock %}

paper/templates/paper/paper_results.html
{% extends "user/navigation_bar_generic.html" %}
{% load static %}

{% block extra-css %}
<link rel="stylesheet" href="{% static 'paper/css/style_resultPage.css'%}">
<style>
  .sidebar {
    display: none;
    position: absolute;
    right: 0;
    width: 300px;
    height: 100%;
    background-color: #f9f9f9;
    padding: 20px;
    box-sizing: border-box;
  }

  .save-button {
    margin-top: 20px;
  }
</style>
{% endblock %}

{% block heading %}
Research Paper Results
{% endblock %}

{% block content %}
{% for paper in papers.data %}
<div class="paper" style="display: flex; justify-content: space-between;">
  <div class="paper-left">
    <h2>{{ paper.title }}
      <a href="{{ paper.url }}">Read More</a>
      <button class="save-button" style="float: right;">Save</button>
    </h2>
    <p>Authors:
      {% for author in paper.authors %}
      {{ author.name }}{% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p>Abstract: {{ paper.abstract }}</p>
  </div>
  <div style="clear: both;"></div>

  <div class="paper-right" data-paper="{{ paper.paperId }}">
    <p>
      <span class="sub-title-icon">&#128197;</span>
      Year: {{ paper.year }}
    </p>
    <p>
      <span class="sub-title-icon">&#128218;</span>
      References: {{ paper.referenceCount }}
    </p>
    <p>
      <span class="sub-title-icon">&#128203;</span>
      Citations: {{ paper.citationCount }}
    </p>
    <p>
      <span class="sub-title-icon">&#127891;</span>
      Fields of Study: <br>
      {% for field in paper.fieldsOfStudy %}
    <div class="field-of-study">{{ field }}</div><br>
    {% endfor %}
    </p>
    <div>  
      <form action="{% url 'paper:graph' %}" class="button">
        <input type="hidden" name="paperId" value="{{ paper.paperId }}">
        <input type="radio" id="citation-graph" name="graphType" value="citations">
        <label for="citation-graph">Citation Graph</label>
        <input type="radio" id="reference-graph" name="graphType" value="references">
        <label for="reference-graph">Reference Graph</label>
        <button class="view-button" id="send-paperId" type="submit">View</button>
        
      </form>
      
      

      <div class="sidebar" style="display:none;">
        <h2>Your Libraries</h2>
        <ul class="library-list"></ul>
        <input class="new-library-name" type="text" placeholder="New Library Name">
        <button class="new-library-button">Create New Library</button>
      </div>
    </div>
  </div>
</div>
{% empty %}
<p>No papers found.</p>
{% endfor %}
{% block pagination %}
{% include 'paper/pagination.html' with page=page query=query total_page=total_page searchPaper=searchPaper%}
{% endblock %}
<script>
  window.onload = function () {
    var colorMap = {
      a: '#FF0000',
      b: '#8aabe5',
      c: '#00FFFF',
      d: '#00008B',
      e: '#FFD700',
      f: '#228B22',
      g: '#808080',
      h: '#FF69B4',
      i: '#4B0082',
      j: '#F0E68C',
      k: '#ADD8E6',
      l: '#00FF00',
      m: '#dea3cc',
      n: '#000080',
      o: '#808000',
      p: '#de8ae5',
      q: '#FFC0CB',
      r: '#FF0000',
      s: '#C0C0C0',
      t: '#008080',
      u: '#800080',
      v: '#EE82EE',
      w: '#F5DEB3',
      x: '#006400',
      y: '#FFFF00',
      z: '#F0FFFF'
    };

    var fields = document.getElementsByClassName('field-of-study');
    for (var i = 0; i < fields.length; i++) {
      var firstLetter = fields[i].innerText.charAt(0).toLowerCase();
      fields[i].style.backgroundColor = colorMap[firstLetter] || '#808080';
    }
  }
</script>
<script>
  // Add event listeners to all the save buttons
  document.querySelectorAll('.paper-right').forEach(paperElement => {
    const paperId = paperElement.getAttribute('data-paper');
    const sidebar = paperElement.querySelector('.sidebar');

    paperElement.querySelector('.save-button').addEventListener('click', function () {
      sidebar.style.display = 'block';

      // Use Ajax to fetch the user's libraries
      fetch('/libraries/')
        .then(response => response.json())
        .then(data => {
          const libraryList = sidebar.querySelector('.library-list');
          libraryList.innerHTML = '';
          data.forEach(library => {
            const listItem = document.createElement('li');
            listItem.textContent = library.name;
            listItem.addEventListener('click', function () {
              // Use Ajax to save the paper to the selected library
              fetch(`/libraries/${library.id}/papers/`, {
                method: 'POST',
                params: JSON.stringify({ paperId: paperId }),
                headers: { 'Content-Type': 'application/json' }
              }).then(() => alert('Paper saved!'));
            });
            libraryList.appendChild(listItem);
          });
        });
    });

    sidebar.querySelector('.new-library-button').addEventListener('click', function () {
      const newLibraryName = sidebar.querySelector('.new-library-name').value;
      if (!newLibraryName) {
        alert('Please enter a name for the new library.');
        return;
      }

      // Use Ajax to create a new library
      fetch('/libraries/', {
        method: 'POST',
        body: JSON.stringify({ name: newLibraryName }),
        headers: { 'Content-Type': 'application/json' }
      }).then(() => alert('New library created!'));
    });
  });
</script>

{% endblock %}