infiniCite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paper.urls')),
    path('user/', include('user.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paper/urls.py
# BEGIN: 5d8f9a2b8d7c
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import LibraryViewSet, LibraryPaperViewSet, PaperView, LibraryView
from . import views

app_name = "paper"
router = DefaultRouter()
router.register(r"libraries", LibraryViewSet)
# TODO: add unshare endpoint
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("graph/", views.graph, name="graph"),
    path("libraries/papers", PaperView.as_view(), name="library-all-papers"),
    path(
        "libraries/<int:library_pk>/papers/",
        LibraryView.as_view(),
        name="library-paper-list",
    ),
    path("api/", include(router.urls)),
    path("api/autocomplete/", views.autocomplete, name="autocomplete"),
    path(
        "api/libraries/<int:library_pk>/share/",
        LibraryViewSet.as_view({"post": "share", "delete": "share"}),
        name="library-share",
    ),
    path(
        "api/libraries/<int:library_pk>/papers/",
        LibraryPaperViewSet.as_view({"post": "create"}),
        name="library-paper-add",
    ),
    path(
        "api/libraries/<int:library_pk>/papers/<str:pk>/",
        LibraryPaperViewSet.as_view({"delete": "destroy"}),
        name="library-paper-remove",
    ),
    path(
        "api/libraries/<int:library_pk>/papers/<str:pk>/move/",
        LibraryPaperViewSet.as_view({"post": "move"}),
        name="library-paper-move",
    ),
    path(
        "api/paper/<str:paper_pk>/libraries/",
        LibraryPaperViewSet.as_view(
            {"post": "add_to_libraries", "delete": "remove_from_libraries"}
        ),
        name="paper-batch-operations",
    ),
    path(
        "api/paper/search/",
        LibraryPaperViewSet.as_view({"post": "search"}),  # later change to post
        name="paper-search",
    ),
    path(
        "api/paper/semantic-search/",
        LibraryPaperViewSet.as_view({"post": "semantic_search"}),
        name="paper-semantic-search",
    ),
    path(
        "api/paper/natural-language-search/",
        LibraryPaperViewSet.as_view({"post": "natural_language_search"}),
        name="paper-natural-language-search",
    ),
    path("paper/home_page.html", views.home_page, name="home_page"),
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # create customized logout view
    path('reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset'),
    path('reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # TODO: change url path to `api/user/search`
    path('api/search/', views.AccountViewSet.as_view({'post': 'search'}), name='search'),
    path('edit/', views.edit, name='edit'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<div class="navbar navbar-expand-lg">
  {% if user.is_authenticated %}
  <div class="function-icon-container" id="menu-icon-container" data-menu-icon-btn>
    <i class="bi bi-layout-sidebar icon"></i>
  </div>
  {% endif %}
  <a class="navbar-brand" href="/">
    <img src="{%static 'assets/star-1.svg'%}" alt="logo" height="30" width="30">
    InfiniCite
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-5">
      <li class="nav-item dropdown">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>

    {% if request.path != '/' %}
    <form class="form-inline my-2 my-lg-0 nav-search-bar" action="{% url 'paper:search'%}">
      <div class="autocompletion-container">
        <input name="query" id="query-field" class="form-control search-box" type="text" placeholder="Search"
          aria-label="Search" value="{{ query }}">
        <ul id="autocomplete-results" class="autocomplete-active"></ul>
      </div>
      {% if searchPaper is null %}
      <input type="hidden" name="searchPaper" value="true" id="paper-search">
      {% else %}
      <input type="hidden" name="searchPaper" value="{{ searchPaper }}" id="paper-search">
      {% endif %}
      <button class="btn btn-outline-success my-2 my-sm-0 ml-2" type="submit">Search</button>
    </form>
    {% endif %}

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <div class="dropdown">
          <button type="button" class="btn btn-primary dropdown-toggle" role="menu" id="navbarDropdown"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle"></i> Account
          </button>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
            <a class="dropdown-item" href="{% url 'user:edit' %}">Settings</a>
          </div>
        </div>
      </li>
      {% else %}
      <li class="nav-item dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" id="navbarDropdown" role="button"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle"></i> Login
        </button>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'user:login' %}">Sign In</a>
          <a class="dropdown-item" href="{% url 'user:register' %}">Sign Up</a>
        </div>
      </li>
      {% endif %}
    </ul>
  </div>
</div>

templates/pagination.html
<div id="pagination">  
  <ul class="page">
    {% if page > 1 %}
      <a href="?query={{ query }}&page=1&searchPaper={{searchPaper}}">&laquo;</a>
      <a href="?query={{ query }}&page={{ page|add:"-1" }}&searchPaper={{searchPaper}}">previous</a>
    {% endif %}
    
    {% for page_num in pages_to_show %}
      {% if page_num == page %}
        <li class="page__numbers active">{{ page_num }}</li>
      {% else %}
        <li class="page__numbers"><a href="?query={{ query }}&page={{ page_num }}&searchPaper={{searchPaper}}">{{ page_num }}</a></li>
      {% endif %}
    {% endfor %}
    
    {% if page < total_pages %}
      <a href="?query={{ query }}&page={{ page|add:"1" }}&searchPaper={{searchPaper}}">next</a>
      <a href="?query={{ query }}&page={{ total_pages }}&searchPaper={{searchPaper}}">&raquo;</a>
    {% endif %}
  </ul>
</div>